<Project Sdk="Godot.NET.Sdk/4.6.1">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <TargetFramework Condition=" '$(GodotTargetPlatform)' == 'android' ">net9.0</TargetFramework>
    <EnableDynamicLoading>true</EnableDynamicLoading>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="Scripts\0.Core\TheDungeon.Core.csproj" />
    <ProjectReference Include="Scripts\1.Content\TheDungeon.Content.csproj" />
    <ProjectReference Include="Scripts\2.State\TheDungeon.State.csproj" />
    <ProjectReference Include="Scripts\3.Game.Contracts\TheDungeon.Game.Contracts.csproj" />
    <ProjectReference Include="Scripts\3.Game\TheDungeon.Game.csproj" />
    <ProjectReference Include="Scripts\4.UI\TheDungeon.UI.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="Scripts\**\*.cs" />
  </ItemGroup>
</Project>
